name: Build Feed JSON

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm uninstall rss-parser
          npm install rss-parser@3.12.2
          npm install node-fetch cheerio

      - run: node build.js

      - name: Commit and Push Feed JSON
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/latest.json
          git commit -m "Update feed" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
