name: Build Feed JSON

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install rss-parser
      - run: node build.js
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add latest.json
          git commit -m "Update feed"
          git push
